---
- name: Listen for events on a webhook
  hosts: all

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 8081
        token: redacted

  ## Define the conditions we are looking for

  rules:
    - name: PostGreSQL Terminate Connections
      condition: event.payload.rule == "terminate_connections"

  ## Define the action we should take should the condition be met
      action:
        run_playbook:
          name: playbooks/pg_terminate_connections.yml
          extra_vars:
            database: "{{ event.payload.database }}"